<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'appointment' => '/../src/Appointment.php',
                'appointmenttest' => '/AppointmentTest.php',
                'email' => '/../src/Email.php',
                'emailtest' => '/EmailTest.php',
                'nickname' => '/../src/Nickname.php',
                'nicknametest' => '/NicknameTest.php',
                'user' => '/../src/User.php',
                'usercollection' => '/../src/UserCollection.php',
                'usercollectiontest' => '/UserCollectionTest.php',
                'userhelpertrait' => '/UserHelperTrait.php',
                'usertest' => '/UserTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
