<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'appointment' => '/../src/Appointment.php',
                'appointmenttest' => '/AppointmentTest.php',
                'appointmenttitle' => '/../src/AppointmentTitle.php',
                'appointmenttitletest' => '/AppointmentTitleTest.php',
                'email' => '/../src/Email.php',
                'emailtest' => '/EmailTest.php',
                'nickname' => '/../src/Nickname.php',
                'nicknametest' => '/NicknameTest.php',
                'room' => '/../src/Room.php',
                'roomcollection' => '/../src/RoomCollection.php',
                'roomcollectiontest' => '/RoomCollectionTest.php',
                'roomtest' => '/RoomTest.php',
                'schedule' => '/../src/Schedule.php',
                'scheduletest' => '/ScheduleTest.php',
                'user' => '/../src/User.php',
                'usercollection' => '/../src/UserCollection.php',
                'usercollectiontest' => '/UserCollectionTest.php',
                'userhelpertrait' => '/UserHelperTrait.php',
                'usertest' => '/UserTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
